#!/usr/bin/env python3
"""
gate_check.py — Phase 0 결정론적 사전 검증 (16개 규칙 전체)

이 스크립트가 Gate를 판단합니다.
  exit code 0 = Gate OPEN  (진행 가능)
  exit code 1 = Gate BLOCKED (CRITICAL 실패 존재)
  exit code 2 = Gate WARN  (HIGH 경고, 사용자 확인 필요)

Usage:
  python3 scripts/gate_check.py \\
    --cluster-name my-cluster \\
    --current-version 1.33 \\
    --target-version 1.34 \\
    [--tf-dir /path/to/terraform] \\
    [--audit-log audit.log]

16개 사전 검증 규칙을 결정론적으로 실행합니다.
--tf-dir 제공 시 INF-001/INF-004 (Terraform drift/recreate) 검증을 추가 실행합니다.
"""

import argparse
import json
import re
import subprocess
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

# ── 색상 (터미널) ──────────────────────────────────────────
RED = "\033[0;31m"
YELLOW = "\033[0;33m"
GREEN = "\033[0;32m"
CYAN = "\033[0;36m"
NC = "\033[0m"

# ── 결과 카운터 ──────────────────────────────────────────
critical_fail = 0
high_warn = 0
total_pass = 0
total_rules = 0


# ── 감사 로그 ──────────────────────────────────────────────
audit_lines: list[str] = []


def audit_init(cluster_name: str, current_ver: str, target_ver: str) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    audit_lines.extend([
        "# K8s Upgrade Pre-flight Audit Log",
        "# Generated by gate_check.py (deterministic)",
        f"# Cluster: {cluster_name}",
        f"# Upgrade: {current_ver} → {target_ver}",
        f"# Started: {now}",
        "# ──────────────────────────────────────────",
    ])


def audit_write(rule_id: str, result: str, detail: str) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    audit_lines.append(f"{now} | {rule_id} | {result} | {detail}")


def audit_flush(path: str) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    gate = "OPEN" if critical_fail == 0 else "BLOCKED"
    audit_lines.extend([
        "# ──────────────────────────────────────────",
        f"# Summary: CRITICAL_FAIL={critical_fail} HIGH_WARN={high_warn} PASS={total_pass}/{total_rules}",
        f"# Gate: {gate}",
        f"# Finished: {now}",
    ])
    Path(path).write_text("\n".join(audit_lines) + "\n", encoding="utf-8")


# ── 결과 기록 ──────────────────────────────────────────────
def record(rule_id: str, severity: str, result: str, detail: str) -> None:
    global critical_fail, high_warn, total_pass, total_rules
    total_rules += 1

    if result == "PASS" or result == "SKIP":
        total_pass += 1
        icon = f"{GREEN}✅ PASS{NC}" if result == "PASS" else f"{CYAN}⏭️  SKIP{NC}"
        print(f"{icon}  {rule_id:<8s} {detail}")
    elif result == "FAIL":
        if severity == "CRITICAL":
            critical_fail += 1
            print(f"{RED}❌ FAIL{NC}  {rule_id:<8s} [{severity}] {detail}")
        else:
            high_warn += 1
            print(f"{YELLOW}⚠️  WARN{NC}  {rule_id:<8s} [{severity}] {detail}")

    audit_write(rule_id, result, detail)


# ── CLI 헬퍼 ──────────────────────────────────────────────
def run_cmd(args: list[str], timeout: int = 30) -> subprocess.CompletedProcess:
    """subprocess wrapper — 실패 시 빈 stdout 반환."""
    try:
        return subprocess.run(args, capture_output=True, text=True, timeout=timeout)
    except (subprocess.TimeoutExpired, FileNotFoundError) as e:
        return subprocess.CompletedProcess(args, returncode=1, stdout="", stderr=str(e))


def kubectl_json(resource: str, all_ns: bool = True, timeout: int = 30) -> dict:
    """kubectl get <resource> -o json 실행 후 dict 반환."""
    cmd = ["kubectl", "get", resource, "-o", "json"]
    if all_ns:
        cmd.insert(2, "-A")
    r = run_cmd(cmd, timeout=timeout)
    if r.returncode != 0:
        return {}
    try:
        return json.loads(r.stdout)
    except json.JSONDecodeError:
        return {}


# ══════════════════════════════════════════════════════════════
# COM-002: 버전 호환성 검증 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_com002(current_version: str, target_version: str) -> None:
    curr_minor = int(current_version.split(".")[1])
    targ_minor = int(target_version.split(".")[1])
    gap = targ_minor - curr_minor

    if gap == 1:
        record("COM-002", "CRITICAL", "PASS",
               f"버전 gap=1 ({current_version} → {target_version})")
    elif gap == 0:
        record("COM-002", "CRITICAL", "SKIP", "이미 동일 버전")
    elif gap > 1:
        record("COM-002", "CRITICAL", "FAIL",
               f"버전 건너뛰기 불가 (gap={gap})")
    else:
        record("COM-002", "CRITICAL", "FAIL",
               f"다운그레이드 불가 (gap={gap})")


# ══════════════════════════════════════════════════════════════
# COM-001: 클러스터 기본 상태 검증 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_com001(cluster_name: str) -> None:
    # 1. EKS 클러스터 상태
    r = run_cmd([
        "aws", "eks", "describe-cluster",
        "--name", cluster_name,
        "--query", "cluster.status",
        "--output", "text",
    ])
    status = r.stdout.strip() if r.returncode == 0 else "ERROR"

    if status != "ACTIVE":
        record("COM-001", "CRITICAL", "FAIL",
               f"클러스터 상태: {status} (ACTIVE 아님)")
        return

    # 2. 노드 상태
    nodes = kubectl_json("nodes", all_ns=False)
    if not nodes:
        record("COM-001", "CRITICAL", "FAIL", "kubectl 연결 실패")
        return

    not_ready = 0
    pressure = 0
    for node in nodes.get("items", []):
        conditions = {
            c["type"]: c["status"]
            for c in node.get("status", {}).get("conditions", [])
        }
        if conditions.get("Ready") != "True":
            not_ready += 1
        for ctype in ("MemoryPressure", "DiskPressure", "PIDPressure"):
            if conditions.get(ctype) == "True":
                pressure += 1

    if not_ready > 0:
        record("COM-001", "CRITICAL", "FAIL",
               f"NotReady 노드 {not_ready}개")
        return
    if pressure > 0:
        record("COM-001", "CRITICAL", "FAIL",
               f"리소스 압박 노드 {pressure}개")
        return

    record("COM-001", "CRITICAL", "PASS",
           "클러스터 ACTIVE, 전 노드 Ready, 압박 없음")


# ══════════════════════════════════════════════════════════════
# COM-002a: kubelet 버전 skew 검증 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_com002a(target_version: str) -> None:
    targ_minor = int(target_version.split(".")[1])
    nodes = kubectl_json("nodes", all_ns=False)
    violations = 0
    for node in nodes.get("items", []):
        ver = node["status"]["nodeInfo"]["kubeletVersion"]
        node_minor = int(ver.split(".")[1])
        if targ_minor - node_minor > 2:
            violations += 1

    if violations > 0:
        record("COM-002a", "CRITICAL", "FAIL",
               f"kubelet skew > 2 노드 {violations}개")
    else:
        record("COM-002a", "CRITICAL", "PASS",
               "kubelet skew 정상 (모두 ≤ 2)")


# ══════════════════════════════════════════════════════════════
# COM-003: Add-on 호환성 검증 (HIGH)
# ══════════════════════════════════════════════════════════════
def check_com003(cluster_name: str, target_version: str) -> None:
    """COM-003: EKS Add-on 상태 및 TARGET_VERSION 호환성 검증."""
    # 1. Add-on 목록 조회
    r = run_cmd([
        "aws", "eks", "list-addons",
        "--cluster-name", cluster_name,
        "--output", "json",
    ])
    if r.returncode != 0:
        record("COM-003", "HIGH", "FAIL", "Add-on 목록 조회 실패")
        return

    try:
        addons = json.loads(r.stdout).get("addons", [])
    except json.JSONDecodeError:
        record("COM-003", "HIGH", "FAIL", "Add-on 목록 JSON 파싱 실패")
        return

    if not addons:
        record("COM-003", "HIGH", "PASS", "Add-on 없음")
        return

    # 2. 각 Add-on 상태 확인
    bad_addons: list[str] = []
    for addon in addons:
        r = run_cmd([
            "aws", "eks", "describe-addon",
            "--cluster-name", cluster_name,
            "--addon-name", addon,
            "--output", "json",
        ])
        if r.returncode != 0:
            continue
        try:
            status = json.loads(r.stdout).get("addon", {}).get("status", "")
        except json.JSONDecodeError:
            continue
        if status in ADDON_BAD_STATES:
            bad_addons.append(f"{addon}({status})")

    if bad_addons:
        record("COM-003", "HIGH", "FAIL",
               f"비정상 Add-on: {', '.join(bad_addons)}")
        return

    # 3. TARGET_VERSION 호환 버전 확인
    incompatible: list[str] = []
    for addon in addons:
        r = run_cmd([
            "aws", "eks", "describe-addon-versions",
            "--addon-name", addon,
            "--kubernetes-version", target_version,
            "--output", "json",
        ])
        if r.returncode != 0:
            incompatible.append(addon)
            continue
        try:
            versions = json.loads(r.stdout).get("addons", [])
        except json.JSONDecodeError:
            incompatible.append(addon)
            continue
        if not versions:
            incompatible.append(addon)

    if incompatible:
        record("COM-003", "HIGH", "FAIL",
               f"TARGET_VERSION {target_version} 비호환 Add-on: {', '.join(incompatible)}")
    else:
        record("COM-003", "HIGH", "PASS",
               f"모든 Add-on ACTIVE + {target_version} 호환")


# ══════════════════════════════════════════════════════════════
# WLS-001: PDB 차단 가능성 분석 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_wls001() -> None:
    data = kubectl_json("pdb")
    blocked = 0
    for pdb in data.get("items", []):
        allowed = pdb.get("status", {}).get("disruptionsAllowed", 1)
        expected = pdb.get("status", {}).get("expectedPods", 0)
        if expected > 0 and allowed == 0:
            ns = pdb["metadata"]["namespace"]
            name = pdb["metadata"]["name"]
            print(f"  BLOCKED: {ns}/{name} (disruptionsAllowed=0)",
                  file=sys.stderr)
            blocked += 1

    if blocked > 0:
        record("WLS-001", "CRITICAL", "FAIL",
               f"PDB 차단 {blocked}개 (disruptionsAllowed=0)")
    else:
        record("WLS-001", "CRITICAL", "PASS",
               "모든 PDB disruptionsAllowed >= 1")


# ══════════════════════════════════════════════════════════════
# WLS-002: 단일 레플리카 서비스 중단 위험 (HIGH)
# ══════════════════════════════════════════════════════════════
SYSTEM_NS = frozenset({
    "kube-system", "kube-node-lease", "kube-public",
    "karpenter", "cert-manager",
})

# ── INF-004 Data Plane 리소스 타입 ──
DATA_PLANE_RESOURCES: frozenset = frozenset({
    "aws_eks_node_group",
    "aws_launch_template",
    "aws_autoscaling_group",
})

# ── INF-004 Recreate 마커 정규식 ──
RECREATE_MARKERS = re.compile(r"forces replacement|must be replaced")
REPLACE_PREFIX = re.compile(r"^\s*-/\+\s+resource\s+\"(\w+)\"\s+\"(\w+)\"", re.MULTILINE)

# ── INF-001 Destroy/Recreate 패턴 ──
DESTROY_PATTERN = re.compile(r"Plan:.*\d+\s+to\s+destroy")

# ── COM-003 비정상 Add-on 상태 ──
ADDON_BAD_STATES: frozenset = frozenset({"DEGRADED", "CREATE_FAILED"})


def check_wls002() -> None:
    count = 0
    for kind in ("deployments", "statefulsets"):
        data = kubectl_json(kind)
        for item in data.get("items", []):
            ns = item["metadata"]["namespace"]
            if ns in SYSTEM_NS:
                continue
            replicas = item.get("spec", {}).get("replicas", 1)
            if replicas == 1:
                name = item["metadata"]["name"]
                k = item.get("kind", kind)
                print(f"  {ns}/{name} ({k}): replicas=1", file=sys.stderr)
                count += 1

    if count > 0:
        record("WLS-002", "HIGH", "FAIL",
               f"단일 레플리카 워크로드 {count}개 (다운타임 위험)")
    else:
        record("WLS-002", "HIGH", "PASS",
               "단일 레플리카 워크로드 없음")


# ══════════════════════════════════════════════════════════════
# WLS-003: PV 존 어피니티 재스케줄 불가 위험 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_wls003() -> None:
    pvs = kubectl_json("pv", all_ns=False)
    nodes = kubectl_json("nodes", all_ns=False)

    if not pvs or not nodes:
        record("WLS-003", "CRITICAL", "PASS", "PV 또는 노드 조회 불가 — 건너뜀")
        return

    # AZ별 노드 수
    az_count: Counter = Counter()
    for n in nodes.get("items", []):
        az = n["metadata"].get("labels", {}).get(
            "topology.kubernetes.io/zone", "")
        if az:
            az_count[az] += 1

    # PV별 위험 판정
    risks = 0
    for pv in pvs.get("items", []):
        if pv.get("status", {}).get("phase") != "Bound":
            continue
        na = (pv.get("spec", {})
              .get("nodeAffinity", {})
              .get("required", {})
              .get("nodeSelectorTerms", []))
        for term in na:
            for expr in term.get("matchExpressions", []):
                if "zone" in expr.get("key", ""):
                    for az in expr.get("values", []):
                        if az_count.get(az, 0) <= 1:
                            claim = pv.get("spec", {}).get("claimRef", {})
                            ns = claim.get("namespace", "?")
                            name = claim.get("name", "?")
                            print(
                                f"  RISK: {ns}/{name} → AZ={az} "
                                f"(노드 {az_count.get(az, 0)}개)",
                                file=sys.stderr,
                            )
                            risks += 1

    if risks > 0:
        record("WLS-003", "CRITICAL", "FAIL",
               f"PV AZ 위험 {risks}개 (drain 시 재스케줄 불가)")
    else:
        record("WLS-003", "CRITICAL", "PASS", "PV AZ 위험 없음")


# ══════════════════════════════════════════════════════════════
# WLS-004: 로컬 스토리지 Pod 데이터 유실 위험 (MEDIUM)
# ══════════════════════════════════════════════════════════════
def check_wls004() -> None:
    pods = kubectl_json("pods", timeout=60)
    if not pods:
        record("WLS-004", "MEDIUM", "PASS", "Pod 조회 불가 — 건너뜀")
        return

    hostpath_count = 0
    for pod in pods.get("items", []):
        ns = pod["metadata"]["namespace"]
        if ns in SYSTEM_NS:
            continue
        phase = pod.get("status", {}).get("phase", "")
        if phase not in ("Running", "Pending"):
            continue
        for vol in pod.get("spec", {}).get("volumes", []):
            if vol.get("hostPath") is not None:
                name = pod["metadata"]["name"]
                path = vol["hostPath"].get("path", "")
                print(f"  hostPath: {ns}/{name} path={path}",
                      file=sys.stderr)
                hostpath_count += 1

    if hostpath_count > 0:
        record("WLS-004", "MEDIUM", "FAIL",
               f"hostPath 사용 Pod {hostpath_count}개 (노드 교체 시 데이터 유실)")
    else:
        record("WLS-004", "MEDIUM", "PASS",
               "hostPath 사용 Pod 없음")


# ══════════════════════════════════════════════════════════════
# WLS-005: 장시간 Job/CronJob 중단 위험 (MEDIUM)
# ══════════════════════════════════════════════════════════════
def check_wls005() -> None:
    pods = kubectl_json("pods", timeout=60)
    if not pods:
        record("WLS-005", "MEDIUM", "PASS", "Pod 조회 불가 — 건너뜀")
        return

    now = datetime.now(timezone.utc)
    risky_jobs = 0
    for pod in pods.get("items", []):
        phase = pod.get("status", {}).get("phase", "")
        if phase != "Running":
            continue
        owners = pod.get("metadata", {}).get("ownerReferences", [])
        is_job = any(o.get("kind") == "Job" for o in owners)
        if not is_job:
            continue

        ns = pod["metadata"]["namespace"]
        name = pod["metadata"]["name"]
        start_str = pod.get("status", {}).get("startTime", "")
        restart_policy = pod.get("spec", {}).get("restartPolicy", "Always")

        if start_str:
            start_dt = datetime.fromisoformat(
                start_str.replace("Z", "+00:00"))
            age_min = (now - start_dt).total_seconds() / 60
        else:
            age_min = 0

        if age_min > 30 or restart_policy == "Never":
            print(f"  Job: {ns}/{name} age={int(age_min)}min "
                  f"restart={restart_policy}", file=sys.stderr)
            risky_jobs += 1

    if risky_jobs > 0:
        record("WLS-005", "MEDIUM", "FAIL",
               f"위험 Job Pod {risky_jobs}개 (age>30min 또는 restartPolicy=Never)")
    else:
        record("WLS-005", "MEDIUM", "PASS",
               "위험 Job Pod 없음")


# ══════════════════════════════════════════════════════════════
# WLS-006: 토폴로지 제약 위반 검증 (HIGH)
# ══════════════════════════════════════════════════════════════
def check_wls006() -> None:
    """WLS-006: TopologySpreadConstraints / Required Affinity 위험 분석."""
    risky: list[str] = []

    for kind in ("deployments", "statefulsets"):
        data = kubectl_json(kind)
        for item in data.get("items", []):
            ns = item["metadata"]["namespace"]
            if ns in SYSTEM_NS:
                continue
            name = item["metadata"]["name"]
            spec = item.get("spec", {}).get("template", {}).get("spec", {})

            # TSC: whenUnsatisfiable == DoNotSchedule
            for tsc in spec.get("topologySpreadConstraints", []):
                if tsc.get("whenUnsatisfiable") == "DoNotSchedule":
                    risky.append(f"{ns}/{name}")
                    break
            else:
                # Affinity: requiredDuringSchedulingIgnoredDuringExecution
                affinity = spec.get("affinity", {})
                node_aff = (affinity.get("nodeAffinity", {})
                            .get("requiredDuringSchedulingIgnoredDuringExecution"))
                pod_anti = (affinity.get("podAntiAffinity", {})
                            .get("requiredDuringSchedulingIgnoredDuringExecution"))
                if node_aff or pod_anti:
                    risky.append(f"{ns}/{name}")

    if not risky:
        record("WLS-006", "HIGH", "PASS",
               "엄격한 토폴로지 제약 워크로드 없음")
        return

    # AZ별 노드 수 확인
    nodes = kubectl_json("nodes", all_ns=False)
    az_count: Counter = Counter()
    for n in nodes.get("items", []):
        az = n["metadata"].get("labels", {}).get(
            "topology.kubernetes.io/zone", "")
        if az:
            az_count[az] += 1

    single_az = [az for az, cnt in az_count.items() if cnt <= 1]

    if single_az:
        record("WLS-006", "HIGH", "FAIL",
               f"위험 워크로드 {len(risky)}개 + 단일 노드 AZ: "
               f"{', '.join(single_az)}")
    else:
        record("WLS-006", "HIGH", "FAIL",
               f"엄격한 토폴로지 제약 워크로드 {len(risky)}개 (drain 시 Pending 위험)")


# ══════════════════════════════════════════════════════════════
# INF-002: 대상 버전 AMI 가용성 검증 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_inf002(target_version: str) -> None:
    ami_found = 0
    ami_missing = 0

    # AL2023
    r = run_cmd([
        "aws", "ssm", "get-parameters-by-path",
        "--path",
        f"/aws/service/eks/optimized-ami/{target_version}"
        "/amazon-linux-2023/x86_64/standard",
        "--recursive",
        "--query", "Parameters | length(@)",
        "--output", "text",
    ])
    al2023 = int(r.stdout.strip()) if r.returncode == 0 and r.stdout.strip().isdigit() else 0

    if al2023 > 0:
        ami_found += 1
    else:
        ami_missing += 1
        print(f"  MISSING: AL2023 x86_64 AMI for {target_version}",
              file=sys.stderr)

    # Bottlerocket
    r = run_cmd([
        "aws", "ssm", "get-parameters-by-path",
        "--path",
        f"/aws/service/bottlerocket/aws-k8s-{target_version}/x86_64",
        "--recursive",
        "--query", "Parameters | length(@)",
        "--output", "text",
    ])
    br = int(r.stdout.strip()) if r.returncode == 0 and r.stdout.strip().isdigit() else 0

    if br > 0:
        ami_found += 1
    else:
        ami_missing += 1
        print(f"  MISSING: Bottlerocket x86_64 AMI for {target_version}",
              file=sys.stderr)

    if ami_missing > 0 and ami_found == 0:
        record("INF-002", "CRITICAL", "FAIL",
               f"AMI 미출시 (AL2023={al2023}, BR={br})")
    elif ami_missing > 0:
        record("INF-002", "CRITICAL", "PASS",
               f"일부 AMI 존재 (AL2023={al2023}, BR={br}) — 사용 중인 타입 확인 필요")
    else:
        record("INF-002", "CRITICAL", "PASS",
               f"모든 AMI 존재 (AL2023={al2023}, BR={br})")


# ══════════════════════════════════════════════════════════════
# CAP-001: 노드 용량 여유분 검증 (HIGH)
# ══════════════════════════════════════════════════════════════
def _parse_cpu(s: str) -> int:
    """CPU 문자열 → 밀리코어."""
    if not s:
        return 0
    if s.endswith("m"):
        return int(s[:-1])
    try:
        return int(float(s) * 1000)
    except ValueError:
        return 0


def _parse_mem(s: str) -> int:
    """메모리 문자열 → MiB."""
    if not s:
        return 0
    if s.endswith("Ki"):
        return int(s[:-2]) // 1024
    if s.endswith("Mi"):
        return int(s[:-2])
    if s.endswith("Gi"):
        return int(float(s[:-2]) * 1024)
    if s.endswith("M"):
        return int(s[:-1])
    try:
        return int(s) // (1024 * 1024)
    except ValueError:
        return 0


def check_cap001() -> None:
    nodes = kubectl_json("nodes", all_ns=False)
    pods = kubectl_json("pods", timeout=60)

    if not nodes or not pods:
        record("CAP-001", "HIGH", "PASS", "노드/Pod 조회 불가 — 건너뜀")
        return

    # 노드 allocatable
    node_alloc: dict[str, dict] = {}
    for node in nodes.get("items", []):
        name = node["metadata"]["name"]
        alloc = node.get("status", {}).get("allocatable", {})
        node_alloc[name] = {
            "cpu": _parse_cpu(alloc.get("cpu", "0")),
            "mem": _parse_mem(alloc.get("memory", "0")),
        }

    # Pod requests 합산
    node_used: dict[str, dict] = defaultdict(lambda: {"cpu": 0, "mem": 0})
    for pod in pods.get("items", []):
        phase = pod.get("status", {}).get("phase", "")
        if phase not in ("Running", "Pending"):
            continue
        node_name = pod.get("spec", {}).get("nodeName", "")
        if not node_name:
            continue
        for container in pod.get("spec", {}).get("containers", []):
            req = container.get("resources", {}).get("requests", {})
            node_used[node_name]["cpu"] += _parse_cpu(req.get("cpu", "0"))
            node_used[node_name]["mem"] += _parse_mem(req.get("memory", "0"))

    # 최대 사용률
    max_pct = 0.0
    for name, alloc in node_alloc.items():
        used = node_used.get(name, {"cpu": 0, "mem": 0})
        if alloc["cpu"] > 0:
            max_pct = max(max_pct, used["cpu"] / alloc["cpu"] * 100)
        if alloc["mem"] > 0:
            max_pct = max(max_pct, used["mem"] / alloc["mem"] * 100)

    util = int(max_pct)
    if util > 90:
        record("CAP-001", "HIGH", "FAIL",
               f"최대 노드 사용률 {util}% (> 90% — Pod Pending 위험)")
    elif util > 80:
        record("CAP-001", "HIGH", "FAIL",
               f"최대 노드 사용률 {util}% (> 80% — drain 시 여유 부족)")
    else:
        record("CAP-001", "HIGH", "PASS",
               f"최대 노드 사용률 {util}% (여유 충분)")


# ══════════════════════════════════════════════════════════════
# CAP-002: 리소스 압박 Pod 검증 (MEDIUM)
# ══════════════════════════════════════════════════════════════
def check_cap002() -> None:
    """CAP-002: OOMKilled, CrashLoopBackOff, ImagePullBackOff, Evicted Pod 감지."""
    pods = kubectl_json("pods", timeout=60)
    if not pods:
        record("CAP-002", "MEDIUM", "PASS", "Pod 조회 불가 — 건너뜀")
        return

    problem_pods: list[str] = []
    evicted_pods: list[str] = []

    for pod in pods.get("items", []):
        ns = pod["metadata"]["namespace"]
        name = pod["metadata"]["name"]

        # Evicted check
        phase = pod.get("status", {}).get("phase", "")
        reason = pod.get("status", {}).get("reason", "")
        if phase == "Failed" and reason == "Evicted":
            evicted_pods.append(f"{ns}/{name}")
            continue

        # containerStatuses check
        for cs in pod.get("status", {}).get("containerStatuses", []):
            # OOMKilled — current state
            term = cs.get("state", {}).get("terminated", {})
            if term.get("reason") == "OOMKilled":
                problem_pods.append(f"{ns}/{name}(OOMKilled)")
                break
            # OOMKilled — last state
            last_term = cs.get("lastState", {}).get("terminated", {})
            if last_term.get("reason") == "OOMKilled":
                problem_pods.append(f"{ns}/{name}(OOMKilled-prev)")
                break
            # CrashLoopBackOff / ImagePullBackOff
            waiting = cs.get("state", {}).get("waiting", {})
            wait_reason = waiting.get("reason", "")
            if wait_reason in ("CrashLoopBackOff", "ImagePullBackOff", "ErrImagePull"):
                problem_pods.append(f"{ns}/{name}({wait_reason})")
                break

    if problem_pods:
        record("CAP-002", "MEDIUM", "FAIL",
               f"문제 Pod {len(problem_pods)}개: "
               f"{', '.join(problem_pods[:5])}"
               f"{'...' if len(problem_pods) > 5 else ''}")
    elif evicted_pods:
        record("CAP-002", "MEDIUM", "PASS",
               f"Evicted Pod {len(evicted_pods)}개 (INFO)")
    else:
        record("CAP-002", "MEDIUM", "PASS", "문제 Pod 없음")


# ══════════════════════════════════════════════════════════════
# CAP-003: Surge 용량 (서브넷 가용 IP) 검증 (HIGH)
# ══════════════════════════════════════════════════════════════
def check_cap003(cluster_name: str) -> None:
    """CAP-003: MNG 서브넷 가용 IP 검증."""
    # 1. MNG 목록 조회
    r = run_cmd([
        "aws", "eks", "list-nodegroups",
        "--cluster-name", cluster_name,
        "--output", "json",
    ])
    if r.returncode != 0:
        record("CAP-003", "HIGH", "FAIL", "MNG 목록 조회 실패")
        return

    try:
        nodegroups = json.loads(r.stdout).get("nodegroups", [])
    except json.JSONDecodeError:
        record("CAP-003", "HIGH", "FAIL", "MNG 목록 JSON 파싱 실패")
        return

    if not nodegroups:
        record("CAP-003", "HIGH", "PASS", "MNG 없음")
        return

    # 2. 각 MNG의 서브넷 수집
    all_subnets: set[str] = set()
    for ng in nodegroups:
        r = run_cmd([
            "aws", "eks", "describe-nodegroup",
            "--cluster-name", cluster_name,
            "--nodegroup-name", ng,
            "--output", "json",
        ])
        if r.returncode != 0:
            continue
        try:
            subnets = json.loads(r.stdout).get("nodegroup", {}).get("subnets", [])
            all_subnets.update(subnets)
        except json.JSONDecodeError:
            continue

    if not all_subnets:
        record("CAP-003", "HIGH", "FAIL", "서브넷 정보 조회 실패")
        return

    # 3. 서브넷 가용 IP 확인
    r = run_cmd([
        "aws", "ec2", "describe-subnets",
        "--subnet-ids", *sorted(all_subnets),
        "--output", "json",
    ])
    if r.returncode != 0:
        record("CAP-003", "HIGH", "FAIL", "서브넷 상세 조회 실패")
        return

    try:
        subnets_data = json.loads(r.stdout).get("Subnets", [])
    except json.JSONDecodeError:
        record("CAP-003", "HIGH", "FAIL", "서브넷 JSON 파싱 실패")
        return

    critical_low: list[str] = []   # < 10
    warning_low: list[str] = []    # 10~49

    for s in subnets_data:
        sid = s.get("SubnetId", "?")
        avail = s.get("AvailableIpAddressCount", 0)
        if avail < 10:
            critical_low.append(f"{sid}({avail})")
        elif avail < 50:
            warning_low.append(f"{sid}({avail})")

    if critical_low:
        record("CAP-003", "HIGH", "FAIL",
               f"가용 IP < 10: {', '.join(critical_low)}")
    elif warning_low:
        record("CAP-003", "HIGH", "FAIL",
               f"가용 IP 10~49 (고갈 위험): {', '.join(warning_low)}")
    else:
        record("CAP-003", "HIGH", "PASS",
               "모든 서브넷 가용 IP ≥ 50")


# ══════════════════════════════════════════════════════════════
# run_terraform_plan: Terraform plan 헬퍼
# ══════════════════════════════════════════════════════════════
def run_terraform_plan(tf_dir: str) -> tuple[int, str]:
    """terraform plan -detailed-exitcode -no-color 실행. 반환: (exit_code, output)."""
    try:
        r = subprocess.run(
            ["terraform", "plan", "-detailed-exitcode", "-no-color"],
            capture_output=True, text=True, cwd=tf_dir, timeout=300,
        )
        return (r.returncode, r.stdout + r.stderr)
    except subprocess.TimeoutExpired:
        return (1, "ERROR: terraform plan timed out (300s)")
    except FileNotFoundError:
        return (1, "ERROR: terraform not found")


# ══════════════════════════════════════════════════════════════
# INF-001: Terraform 상태 드리프트 검증 (HIGH)
# ══════════════════════════════════════════════════════════════
def check_inf001(tf_exit_code: int, plan_output: str) -> None:
    """INF-001: Terraform 상태 드리프트 검증."""
    if tf_exit_code == 0:
        record("INF-001", "HIGH", "PASS", "terraform plan: 변경 없음 (no drift)")
        return
    if tf_exit_code == 1:
        record("INF-001", "HIGH", "FAIL", "terraform plan 오류 (exit code 1)")
        return
    # exit code 2 — changes detected
    if DESTROY_PATTERN.search(plan_output) or RECREATE_MARKERS.search(plan_output):
        record("INF-001", "HIGH", "FAIL",
               "terraform drift 감지 — destroy/recreate 포함")
    else:
        record("INF-001", "HIGH", "FAIL",
               "terraform drift 감지 — 비파괴적 변경")


# ══════════════════════════════════════════════════════════════
# INF-004: Terraform Recreate 감지 — Data Plane 리소스 (HIGH/CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_inf004(plan_output: str) -> None:
    """INF-004: Terraform Recreate 감지 (Data Plane 리소스)."""
    recreate_resources: list[str] = []
    # -/+ resource lines
    for m in REPLACE_PREFIX.finditer(plan_output):
        recreate_resources.append(m.group(1))
    # "forces replacement" / "must be replaced" context lines
    for line in plan_output.splitlines():
        if RECREATE_MARKERS.search(line):
            # Try to extract resource type from nearby context
            # Lines like: # aws_eks_node_group.xxx must be replaced
            parts = line.strip().lstrip("# ").split(".")
            if len(parts) >= 2:
                rtype = parts[0].strip()
                if rtype and rtype[0].isalpha():
                    recreate_resources.append(rtype)

    if not recreate_resources:
        record("INF-004", "HIGH", "PASS", "recreate 마커 없음")
        return

    data_plane_hits = [r for r in recreate_resources if r in DATA_PLANE_RESOURCES]
    if data_plane_hits:
        record("INF-004", "CRITICAL", "FAIL",
               f"Data Plane recreate 감지: {', '.join(set(data_plane_hits))}")
    else:
        record("INF-004", "HIGH", "FAIL",
               f"비-Data Plane recreate: {', '.join(set(recreate_resources))}")


# ══════════════════════════════════════════════════════════════
# INF-003: Karpenter 호환성 검증 (HIGH)
# ══════════════════════════════════════════════════════════════
def check_inf003() -> None:
    """INF-003: Karpenter 호환성 검증."""
    # 1. CRD 존재 확인
    r = run_cmd(["kubectl", "get", "crd", "nodeclaims.karpenter.sh"], timeout=10)
    if r.returncode != 0:
        record("INF-003", "HIGH", "SKIP", "Karpenter CRD 미존재 — 건너뜀")
        return

    # 2. Karpenter 버전 추출
    r = run_cmd([
        "kubectl", "get", "deployment", "-n", "karpenter", "karpenter",
        "-o", "json",
    ])
    version = "unknown"
    if r.returncode == 0:
        try:
            dep = json.loads(r.stdout)
            image = dep["spec"]["template"]["spec"]["containers"][0]["image"]
            version = image.rsplit(":", 1)[-1] if ":" in image else "unknown"
        except (json.JSONDecodeError, KeyError, IndexError):
            pass

    # 3. NodePool disruption budget 확인
    r = run_cmd(["kubectl", "get", "nodepool", "-o", "json"])
    if r.returncode != 0:
        record("INF-003", "HIGH", "PASS",
               f"Karpenter {version} — NodePool 조회 불가")
        return

    try:
        pools = json.loads(r.stdout)
    except json.JSONDecodeError:
        record("INF-003", "HIGH", "PASS",
               f"Karpenter {version} — NodePool JSON 파싱 실패")
        return

    blocked_pools: list[str] = []
    for pool in pools.get("items", []):
        name = pool.get("metadata", {}).get("name", "?")
        budgets = (pool.get("spec", {})
                   .get("disruption", {})
                   .get("budgets", []))
        for b in budgets:
            nodes_val = b.get("nodes", None)
            if nodes_val is not None:
                # "0" or 0
                try:
                    if int(str(nodes_val)) == 0:
                        blocked_pools.append(name)
                        break
                except ValueError:
                    pass

    if blocked_pools:
        record("INF-003", "HIGH", "FAIL",
               f"Karpenter {version} — disruption budget=0: "
               f"{', '.join(blocked_pools)} (drift 교체 차단)")
    else:
        record("INF-003", "HIGH", "PASS",
               f"Karpenter {version} — disruption budget 정상")


# ══════════════════════════════════════════════════════════════
# main
# ══════════════════════════════════════════════════════════════
def main() -> None:
    parser = argparse.ArgumentParser(
        description="Phase 0 결정론적 사전 검증 (gate_check.py)")
    parser.add_argument("--cluster-name", required=True)
    parser.add_argument("--current-version", required=True)
    parser.add_argument("--target-version", required=True)
    parser.add_argument("--audit-log", default="audit.log",
                        help="감사 로그 저장 경로 (기본: 현재 디렉토리의 audit.log)")
    parser.add_argument("--tf-dir", default=None,
                        help="Terraform 구성 디렉토리 (INF-001/INF-004에 필요)")
    args = parser.parse_args()

    # 의존성 확인
    for cmd in ("kubectl", "aws"):
        r = run_cmd(["which", cmd])
        if r.returncode != 0:
            print(f"ERROR: '{cmd}' not found in PATH.", file=sys.stderr)
            sys.exit(127)

    # --tf-dir 검증
    if args.tf_dir:
        tf_path = Path(args.tf_dir)
        if not tf_path.is_dir():
            print(f"ERROR: --tf-dir '{args.tf_dir}' is not a directory.", file=sys.stderr)
            sys.exit(1)
        r = run_cmd(["which", "terraform"])
        if r.returncode != 0:
            print("ERROR: 'terraform' not found in PATH.", file=sys.stderr)
            sys.exit(1)

    print()
    print("════════════════════════════════════════════════════════════")
    print("  Phase 0: 결정론적 사전 검증 (gate_check.py)")
    print(f"  Cluster: {args.cluster_name}")
    print(f"  Upgrade: {args.current_version} → {args.target_version}")
    print("════════════════════════════════════════════════════════════")
    print()

    audit_init(args.cluster_name, args.current_version, args.target_version)

    # ── 전체 규칙 목록 (SKIPPED 추적용) ──
    ALL_RULES = [
        "COM-002", "COM-001", "COM-002a", "COM-003",
        "WLS-001", "WLS-002", "WLS-003", "WLS-004", "WLS-005", "WLS-006",
        "CAP-001", "CAP-002", "CAP-003",
        "INF-001", "INF-002", "INF-003", "INF-004",
    ]
    executed_rules: list[str] = []

    def track(rule_id: str) -> None:
        executed_rules.append(rule_id)

    # ── 1단계: 공통 검증 ──
    print("── 1단계: 공통 검증 ──")
    check_com002(args.current_version, args.target_version)
    track("COM-002")

    # 버전 gap이 0이거나 >1이면 나머지 검증 무의미
    if critical_fail > 0:
        for r in ALL_RULES:
            if r not in executed_rules:
                record(r, "-", "SKIP", "COM-002 CRITICAL FAIL로 인해 건너뜀")
    else:
        check_com001(args.cluster_name)
        track("COM-001")
        check_com002a(args.target_version)
        track("COM-002a")
        check_com003(args.cluster_name, args.target_version)
        track("COM-003")

        # ── 2단계: 워크로드 안전성 ──
        print("\n── 2단계: 워크로드 안전성 ──")
        check_wls001()
        track("WLS-001")
        check_wls002()
        track("WLS-002")
        check_wls003()
        track("WLS-003")
        check_wls004()
        track("WLS-004")
        check_wls005()
        track("WLS-005")
        check_wls006()
        track("WLS-006")

        # ── 3단계: 용량 검증 ──
        print("\n── 3단계: 용량 검증 ──")
        check_cap001()
        track("CAP-001")
        check_cap002()
        track("CAP-002")
        check_cap003(args.cluster_name)
        track("CAP-003")

        # ── 4단계: 인프라 검증 ──
        print("\n── 4단계: 인프라 검증 ──")
        if args.tf_dir:
            tf_exit_code, plan_output = run_terraform_plan(args.tf_dir)
            check_inf001(tf_exit_code, plan_output)
            track("INF-001")
        else:
            record("INF-001", "HIGH", "SKIP", "--tf-dir 미제공")
            track("INF-001")

        check_inf002(args.target_version)
        track("INF-002")
        check_inf003()
        track("INF-003")

        if args.tf_dir:
            check_inf004(plan_output)
            track("INF-004")
        else:
            record("INF-004", "HIGH", "SKIP", "--tf-dir 미제공")
            track("INF-004")

    # ── Gate 판정 ──
    print()
    print("════════════════════════════════════════════════════════════")
    print(f"  결정론적 검증 결과")
    print(f"  총 {total_rules}개 규칙 | PASS: {total_pass} "
          f"| CRITICAL FAIL: {critical_fail} | HIGH WARN: {high_warn}")
    print("════════════════════════════════════════════════════════════")

    audit_flush(args.audit_log)

    if critical_fail > 0:
        print()
        print(f"{RED}Gate: BLOCKED — CRITICAL 실패 {critical_fail}개. "
              f"해결 후 재실행하세요.{NC}")
        print(f"감사 로그: {args.audit_log}")
        sys.exit(1)
    elif high_warn > 0:
        print()
        print(f"{YELLOW}Gate: WARN — HIGH 경고 {high_warn}개. "
              f"사용자 확인 필요.{NC}")
        print(f"감사 로그: {args.audit_log}")
        sys.exit(2)
    else:
        print()
        print(f"{GREEN}Gate: OPEN — 결정론적 검증 통과.{NC}")
        print(f"감사 로그: {args.audit_log}")
        sys.exit(0)


if __name__ == "__main__":
    main()
