#!/usr/bin/env python3
"""
gate_check.py — Phase 0 결정론적 사전 검증

LLM이 아닌 이 스크립트가 Gate를 판단합니다.
  exit code 0 = Gate OPEN  (진행 가능)
  exit code 1 = Gate BLOCKED (CRITICAL 실패 존재)
  exit code 2 = Gate WARN  (HIGH 경고, 사용자 확인 필요)

Usage:
  python3 scripts/gate_check.py \
    --cluster-name my-cluster \
    --current-version 1.33 \
    --target-version 1.34 \
    [--audit-log audit.log]

결정론적으로 판단 가능한 규칙만 실행합니다.
LLM 해석이 필요한 규칙(COM-003, WLS-004~006, INF-001/003/004, CAP-002/003)은
별도로 LLM이 실행하되, 이 스크립트의 Gate가 BLOCKED이면 진행 불가합니다.
"""

import argparse
import json
import subprocess
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

# ── 색상 (터미널) ──────────────────────────────────────────
RED = "\033[0;31m"
YELLOW = "\033[0;33m"
GREEN = "\033[0;32m"
CYAN = "\033[0;36m"
NC = "\033[0m"

# ── 결과 카운터 ──────────────────────────────────────────
critical_fail = 0
high_warn = 0
total_pass = 0
total_rules = 0


# ── 감사 로그 ──────────────────────────────────────────────
audit_lines: list[str] = []


def audit_init(cluster_name: str, current_ver: str, target_ver: str) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    audit_lines.extend([
        "# K8s Upgrade Pre-flight Audit Log",
        "# Generated by gate_check.py (deterministic)",
        f"# Cluster: {cluster_name}",
        f"# Upgrade: {current_ver} → {target_ver}",
        f"# Started: {now}",
        "# ──────────────────────────────────────────",
    ])


def audit_write(rule_id: str, result: str, detail: str) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    audit_lines.append(f"{now} | {rule_id} | {result} | {detail}")


def audit_flush(path: str) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    gate = "OPEN" if critical_fail == 0 else "BLOCKED"
    audit_lines.extend([
        "# ──────────────────────────────────────────",
        f"# Summary: CRITICAL_FAIL={critical_fail} HIGH_WARN={high_warn} PASS={total_pass}/{total_rules}",
        f"# Gate: {gate}",
        f"# Finished: {now}",
    ])
    Path(path).write_text("\n".join(audit_lines) + "\n", encoding="utf-8")


# ── 결과 기록 ──────────────────────────────────────────────
def record(rule_id: str, severity: str, result: str, detail: str) -> None:
    global critical_fail, high_warn, total_pass, total_rules
    total_rules += 1

    if result == "PASS" or result == "SKIP":
        total_pass += 1
        icon = f"{GREEN}✅ PASS{NC}" if result == "PASS" else f"{CYAN}⏭️  SKIP{NC}"
        print(f"{icon}  {rule_id:<8s} {detail}")
    elif result == "FAIL":
        if severity == "CRITICAL":
            critical_fail += 1
            print(f"{RED}❌ FAIL{NC}  {rule_id:<8s} [{severity}] {detail}")
        else:
            high_warn += 1
            print(f"{YELLOW}⚠️  WARN{NC}  {rule_id:<8s} [{severity}] {detail}")

    audit_write(rule_id, result, detail)


# ── CLI 헬퍼 ──────────────────────────────────────────────
def run_cmd(args: list[str], timeout: int = 30) -> subprocess.CompletedProcess:
    """subprocess wrapper — 실패 시 빈 stdout 반환."""
    try:
        return subprocess.run(args, capture_output=True, text=True, timeout=timeout)
    except (subprocess.TimeoutExpired, FileNotFoundError) as e:
        return subprocess.CompletedProcess(args, returncode=1, stdout="", stderr=str(e))


def kubectl_json(resource: str, all_ns: bool = True, timeout: int = 30) -> dict:
    """kubectl get <resource> -o json 실행 후 dict 반환."""
    cmd = ["kubectl", "get", resource, "-o", "json"]
    if all_ns:
        cmd.insert(2, "-A")
    r = run_cmd(cmd, timeout=timeout)
    if r.returncode != 0:
        return {}
    try:
        return json.loads(r.stdout)
    except json.JSONDecodeError:
        return {}


# ══════════════════════════════════════════════════════════════
# COM-002: 버전 호환성 검증 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_com002(current_version: str, target_version: str) -> None:
    curr_minor = int(current_version.split(".")[1])
    targ_minor = int(target_version.split(".")[1])
    gap = targ_minor - curr_minor

    if gap == 1:
        record("COM-002", "CRITICAL", "PASS",
               f"버전 gap=1 ({current_version} → {target_version})")
    elif gap == 0:
        record("COM-002", "CRITICAL", "SKIP", "이미 동일 버전")
    elif gap > 1:
        record("COM-002", "CRITICAL", "FAIL",
               f"버전 건너뛰기 불가 (gap={gap})")
    else:
        record("COM-002", "CRITICAL", "FAIL",
               f"다운그레이드 불가 (gap={gap})")


# ══════════════════════════════════════════════════════════════
# COM-001: 클러스터 기본 상태 검증 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_com001(cluster_name: str) -> None:
    # 1. EKS 클러스터 상태
    r = run_cmd([
        "aws", "eks", "describe-cluster",
        "--name", cluster_name,
        "--query", "cluster.status",
        "--output", "text",
    ])
    status = r.stdout.strip() if r.returncode == 0 else "ERROR"

    if status != "ACTIVE":
        record("COM-001", "CRITICAL", "FAIL",
               f"클러스터 상태: {status} (ACTIVE 아님)")
        return

    # 2. 노드 상태
    nodes = kubectl_json("nodes", all_ns=False)
    if not nodes:
        record("COM-001", "CRITICAL", "FAIL", "kubectl 연결 실패")
        return

    not_ready = 0
    pressure = 0
    for node in nodes.get("items", []):
        conditions = {
            c["type"]: c["status"]
            for c in node.get("status", {}).get("conditions", [])
        }
        if conditions.get("Ready") != "True":
            not_ready += 1
        for ctype in ("MemoryPressure", "DiskPressure", "PIDPressure"):
            if conditions.get(ctype) == "True":
                pressure += 1

    if not_ready > 0:
        record("COM-001", "CRITICAL", "FAIL",
               f"NotReady 노드 {not_ready}개")
        return
    if pressure > 0:
        record("COM-001", "CRITICAL", "FAIL",
               f"리소스 압박 노드 {pressure}개")
        return

    record("COM-001", "CRITICAL", "PASS",
           "클러스터 ACTIVE, 전 노드 Ready, 압박 없음")


# ══════════════════════════════════════════════════════════════
# COM-002b: kubelet 버전 skew 검증 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_com002_skew(target_version: str) -> None:
    targ_minor = int(target_version.split(".")[1])
    nodes = kubectl_json("nodes", all_ns=False)
    violations = 0
    for node in nodes.get("items", []):
        ver = node["status"]["nodeInfo"]["kubeletVersion"]
        node_minor = int(ver.split(".")[1])
        if targ_minor - node_minor > 2:
            violations += 1

    if violations > 0:
        record("COM-002", "CRITICAL", "FAIL",
               f"kubelet skew > 2 노드 {violations}개")
    else:
        record("COM-002", "CRITICAL", "PASS",
               "kubelet skew 정상 (모두 ≤ 2)")


# ══════════════════════════════════════════════════════════════
# WLS-001: PDB 차단 가능성 분석 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_wls001() -> None:
    data = kubectl_json("pdb")
    blocked = 0
    for pdb in data.get("items", []):
        allowed = pdb.get("status", {}).get("disruptionsAllowed", 1)
        expected = pdb.get("status", {}).get("expectedPods", 0)
        if expected > 0 and allowed == 0:
            ns = pdb["metadata"]["namespace"]
            name = pdb["metadata"]["name"]
            print(f"  BLOCKED: {ns}/{name} (disruptionsAllowed=0)",
                  file=sys.stderr)
            blocked += 1

    if blocked > 0:
        record("WLS-001", "CRITICAL", "FAIL",
               f"PDB 차단 {blocked}개 (disruptionsAllowed=0)")
    else:
        record("WLS-001", "CRITICAL", "PASS",
               "모든 PDB disruptionsAllowed >= 1")


# ══════════════════════════════════════════════════════════════
# WLS-002: 단일 레플리카 서비스 중단 위험 (HIGH)
# ══════════════════════════════════════════════════════════════
SYSTEM_NS = frozenset({
    "kube-system", "kube-node-lease", "kube-public",
    "karpenter", "cert-manager",
})


def check_wls002() -> None:
    count = 0
    for kind in ("deployments", "statefulsets"):
        data = kubectl_json(kind)
        for item in data.get("items", []):
            ns = item["metadata"]["namespace"]
            if ns in SYSTEM_NS:
                continue
            replicas = item.get("spec", {}).get("replicas", 1)
            if replicas == 1:
                name = item["metadata"]["name"]
                k = item.get("kind", kind)
                print(f"  {ns}/{name} ({k}): replicas=1", file=sys.stderr)
                count += 1

    if count > 0:
        record("WLS-002", "HIGH", "FAIL",
               f"단일 레플리카 워크로드 {count}개 (다운타임 위험)")
    else:
        record("WLS-002", "HIGH", "PASS",
               "단일 레플리카 워크로드 없음")


# ══════════════════════════════════════════════════════════════
# WLS-003: PV 존 어피니티 재스케줄 불가 위험 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_wls003() -> None:
    pvs = kubectl_json("pv", all_ns=False)
    nodes = kubectl_json("nodes", all_ns=False)

    if not pvs or not nodes:
        record("WLS-003", "CRITICAL", "PASS", "PV 또는 노드 조회 불가 — 건너뜀")
        return

    # AZ별 노드 수
    az_count: Counter = Counter()
    for n in nodes.get("items", []):
        az = n["metadata"].get("labels", {}).get(
            "topology.kubernetes.io/zone", "")
        if az:
            az_count[az] += 1

    # PV별 위험 판정
    risks = 0
    for pv in pvs.get("items", []):
        if pv.get("status", {}).get("phase") != "Bound":
            continue
        na = (pv.get("spec", {})
              .get("nodeAffinity", {})
              .get("required", {})
              .get("nodeSelectorTerms", []))
        for term in na:
            for expr in term.get("matchExpressions", []):
                if "zone" in expr.get("key", ""):
                    for az in expr.get("values", []):
                        if az_count.get(az, 0) <= 1:
                            claim = pv.get("spec", {}).get("claimRef", {})
                            ns = claim.get("namespace", "?")
                            name = claim.get("name", "?")
                            print(
                                f"  RISK: {ns}/{name} → AZ={az} "
                                f"(노드 {az_count.get(az, 0)}개)",
                                file=sys.stderr,
                            )
                            risks += 1

    if risks > 0:
        record("WLS-003", "CRITICAL", "FAIL",
               f"PV AZ 위험 {risks}개 (drain 시 재스케줄 불가)")
    else:
        record("WLS-003", "CRITICAL", "PASS", "PV AZ 위험 없음")


# ══════════════════════════════════════════════════════════════
# INF-002: 대상 버전 AMI 가용성 검증 (CRITICAL)
# ══════════════════════════════════════════════════════════════
def check_inf002(target_version: str) -> None:
    ami_found = 0
    ami_missing = 0

    # AL2023
    r = run_cmd([
        "aws", "ssm", "get-parameters-by-path",
        "--path",
        f"/aws/service/eks/optimized-ami/{target_version}"
        "/amazon-linux-2023/x86_64/standard",
        "--recursive",
        "--query", "Parameters | length(@)",
        "--output", "text",
    ])
    al2023 = int(r.stdout.strip()) if r.returncode == 0 and r.stdout.strip().isdigit() else 0

    if al2023 > 0:
        ami_found += 1
    else:
        ami_missing += 1
        print(f"  MISSING: AL2023 x86_64 AMI for {target_version}",
              file=sys.stderr)

    # Bottlerocket
    r = run_cmd([
        "aws", "ssm", "get-parameters-by-path",
        "--path",
        f"/aws/service/bottlerocket/aws-k8s-{target_version}/x86_64",
        "--recursive",
        "--query", "Parameters | length(@)",
        "--output", "text",
    ])
    br = int(r.stdout.strip()) if r.returncode == 0 and r.stdout.strip().isdigit() else 0

    if br > 0:
        ami_found += 1
    else:
        ami_missing += 1
        print(f"  MISSING: Bottlerocket x86_64 AMI for {target_version}",
              file=sys.stderr)

    if ami_missing > 0 and ami_found == 0:
        record("INF-002", "CRITICAL", "FAIL",
               f"AMI 미출시 (AL2023={al2023}, BR={br})")
    elif ami_missing > 0:
        record("INF-002", "CRITICAL", "PASS",
               f"일부 AMI 존재 (AL2023={al2023}, BR={br}) — 사용 중인 타입 확인 필요")
    else:
        record("INF-002", "CRITICAL", "PASS",
               f"모든 AMI 존재 (AL2023={al2023}, BR={br})")


# ══════════════════════════════════════════════════════════════
# CAP-001: 노드 용량 여유분 검증 (HIGH)
# ══════════════════════════════════════════════════════════════
def _parse_cpu(s: str) -> int:
    """CPU 문자열 → 밀리코어."""
    if not s:
        return 0
    if s.endswith("m"):
        return int(s[:-1])
    try:
        return int(float(s) * 1000)
    except ValueError:
        return 0


def _parse_mem(s: str) -> int:
    """메모리 문자열 → MiB."""
    if not s:
        return 0
    if s.endswith("Ki"):
        return int(s[:-2]) // 1024
    if s.endswith("Mi"):
        return int(s[:-2])
    if s.endswith("Gi"):
        return int(float(s[:-2]) * 1024)
    if s.endswith("M"):
        return int(s[:-1])
    try:
        return int(s) // (1024 * 1024)
    except ValueError:
        return 0


def check_cap001() -> None:
    nodes = kubectl_json("nodes", all_ns=False)
    pods = kubectl_json("pods", timeout=60)

    if not nodes or not pods:
        record("CAP-001", "HIGH", "PASS", "노드/Pod 조회 불가 — 건너뜀")
        return

    # 노드 allocatable
    node_alloc: dict[str, dict] = {}
    for node in nodes.get("items", []):
        name = node["metadata"]["name"]
        alloc = node.get("status", {}).get("allocatable", {})
        node_alloc[name] = {
            "cpu": _parse_cpu(alloc.get("cpu", "0")),
            "mem": _parse_mem(alloc.get("memory", "0")),
        }

    # Pod requests 합산
    node_used: dict[str, dict] = defaultdict(lambda: {"cpu": 0, "mem": 0})
    for pod in pods.get("items", []):
        phase = pod.get("status", {}).get("phase", "")
        if phase not in ("Running", "Pending"):
            continue
        node_name = pod.get("spec", {}).get("nodeName", "")
        if not node_name:
            continue
        for container in pod.get("spec", {}).get("containers", []):
            req = container.get("resources", {}).get("requests", {})
            node_used[node_name]["cpu"] += _parse_cpu(req.get("cpu", "0"))
            node_used[node_name]["mem"] += _parse_mem(req.get("memory", "0"))

    # 최대 사용률
    max_pct = 0.0
    for name, alloc in node_alloc.items():
        used = node_used.get(name, {"cpu": 0, "mem": 0})
        if alloc["cpu"] > 0:
            max_pct = max(max_pct, used["cpu"] / alloc["cpu"] * 100)
        if alloc["mem"] > 0:
            max_pct = max(max_pct, used["mem"] / alloc["mem"] * 100)

    util = int(max_pct)
    if util > 90:
        record("CAP-001", "HIGH", "FAIL",
               f"최대 노드 사용률 {util}% (> 90% — Pod Pending 위험)")
    elif util > 80:
        record("CAP-001", "HIGH", "FAIL",
               f"최대 노드 사용률 {util}% (> 80% — drain 시 여유 부족)")
    else:
        record("CAP-001", "HIGH", "PASS",
               f"최대 노드 사용률 {util}% (여유 충분)")


# ══════════════════════════════════════════════════════════════
# main
# ══════════════════════════════════════════════════════════════
def main() -> None:
    parser = argparse.ArgumentParser(
        description="Phase 0 결정론적 사전 검증 (gate_check.py)")
    parser.add_argument("--cluster-name", required=True)
    parser.add_argument("--current-version", required=True)
    parser.add_argument("--target-version", required=True)
    parser.add_argument("--audit-log", default="audit.log")
    args = parser.parse_args()

    # 의존성 확인
    for cmd in ("kubectl", "aws"):
        r = run_cmd(["which", cmd])
        if r.returncode != 0:
            print(f"ERROR: '{cmd}' not found in PATH.", file=sys.stderr)
            sys.exit(127)

    print()
    print("════════════════════════════════════════════════════════════")
    print("  Phase 0: 결정론적 사전 검증 (gate_check.py)")
    print(f"  Cluster: {args.cluster_name}")
    print(f"  Upgrade: {args.current_version} → {args.target_version}")
    print("════════════════════════════════════════════════════════════")
    print()

    audit_init(args.cluster_name, args.current_version, args.target_version)

    # ── 1단계: 공통 검증 ──
    print("── 1단계: 공통 검증 ──")
    check_com002(args.current_version, args.target_version)
    check_com001(args.cluster_name)
    check_com002_skew(args.target_version)

    # ── 2단계: 워크로드 안전성 ──
    print("\n── 2단계: 워크로드 안전성 ──")
    check_wls001()
    check_wls002()
    check_wls003()

    # ── 3단계: 용량 검증 ──
    print("\n── 3단계: 용량 검증 ──")
    check_cap001()

    # ── 4단계: 인프라 검증 ──
    print("\n── 4단계: 인프라 검증 ──")
    check_inf002(args.target_version)

    # ── Gate 판정 ──
    print()
    print("════════════════════════════════════════════════════════════")
    print(f"  결정론적 검증 결과")
    print(f"  총 {total_rules}개 규칙 | PASS: {total_pass} "
          f"| CRITICAL FAIL: {critical_fail} | HIGH WARN: {high_warn}")
    print("════════════════════════════════════════════════════════════")

    audit_flush(args.audit_log)

    if critical_fail > 0:
        print()
        print(f"{RED}Gate: BLOCKED — CRITICAL 실패 {critical_fail}개. "
              f"해결 후 재실행하세요.{NC}")
        print(f"감사 로그: {args.audit_log}")
        sys.exit(1)
    elif high_warn > 0:
        print()
        print(f"{YELLOW}Gate: WARN — HIGH 경고 {high_warn}개. "
              f"사용자 확인 필요.{NC}")
        print(f"감사 로그: {args.audit_log}")
        sys.exit(2)
    else:
        print()
        print(f"{GREEN}Gate: OPEN — 결정론적 검증 통과. "
              f"LLM 보조 검증 진행 가능.{NC}")
        print(f"감사 로그: {args.audit_log}")
        sys.exit(0)


if __name__ == "__main__":
    main()
