#!/usr/bin/env python3
"""
lib.py — gate_check.py / phase_gate.py 공통 헬퍼 모듈

색상 상수, 시스템 상수, GateResult, audit 함수, record, CLI 헬퍼,
리소스 파서를 단일 모듈로 제공한다.

Python 3.9+ stdlib only — 서드파티 의존성 없음.
"""

import json
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

# ══════════════════════════════════════════════════════════════
# 색상 상수 (터미널)
# ══════════════════════════════════════════════════════════════
RED = "\033[0;31m"
YELLOW = "\033[0;33m"
GREEN = "\033[0;32m"
CYAN = "\033[0;36m"
NC = "\033[0m"

# ══════════════════════════════════════════════════════════════
# 시스템 상수
# ══════════════════════════════════════════════════════════════

# 시스템 네임스페이스 (WLS-002, WLS-004, WLS-005, WLS-006 제외 대상)
SYSTEM_NS = frozenset({
    "kube-system", "kube-node-lease", "kube-public",
    "karpenter", "cert-manager",
    "amazon-cloudwatch", "amazon-guardduty",
    "aws-secrets-manager",
})

# INF-004 Data Plane 리소스 타입
DATA_PLANE_RESOURCES: frozenset = frozenset({
    "aws_eks_node_group",
    "aws_launch_template",
    "aws_autoscaling_group",
})

# COM-003 비정상 Add-on 상태
ADDON_BAD_STATES: frozenset = frozenset({"DEGRADED", "CREATE_FAILED"})


# ══════════════════════════════════════════════════════════════
# GateResult: 검증 상태를 캡슐화하는 클래스 (글로벌 변수 대체)
# ══════════════════════════════════════════════════════════════
@dataclass
class GateResult:
    """Gate 검증 결과를 캡슐화. 글로벌 mutable state 대신 인스턴스 사용."""
    critical_fail: int = 0
    high_warn: int = 0
    medium_info: int = 0
    total_pass: int = 0
    total_rules: int = 0
    audit_lines: list[str] = field(default_factory=list)

    def reset(self) -> None:
        """모든 카운터와 감사 로그 초기화."""
        self.critical_fail = 0
        self.high_warn = 0
        self.medium_info = 0
        self.total_pass = 0
        self.total_rules = 0
        self.audit_lines.clear()


# ══════════════════════════════════════════════════════════════
# 모듈 레벨 호환 패턴 (_gate 인스턴스 + 동기화)
# ══════════════════════════════════════════════════════════════

# 모듈 레벨 기본 인스턴스 (하위 호환)
_gate = GateResult()

# 하위 호환용 모듈 레벨 참조 (테스트에서 lib.critical_fail 등으로 접근)
critical_fail = 0
high_warn = 0
medium_info = 0
total_pass = 0
total_rules = 0
audit_lines: list[str] = []


def _sync_from_gate() -> None:
    """_gate 인스턴스의 값을 모듈 레벨 변수에 동기화 (하위 호환)."""
    global critical_fail, high_warn, medium_info, total_pass, total_rules, audit_lines
    critical_fail = _gate.critical_fail
    high_warn = _gate.high_warn
    medium_info = _gate.medium_info
    total_pass = _gate.total_pass
    total_rules = _gate.total_rules
    audit_lines = _gate.audit_lines


def _sync_to_gate() -> None:
    """모듈 레벨 변수의 값을 _gate 인스턴스에 동기화 (테스트에서 직접 수정 시)."""
    _gate.critical_fail = critical_fail
    _gate.high_warn = high_warn
    _gate.medium_info = medium_info
    _gate.total_pass = total_pass
    _gate.total_rules = total_rules
    # audit_lines는 참조 동기화 — 새 리스트 할당 시 방어
    if audit_lines is not _gate.audit_lines:
        _gate.audit_lines = audit_lines


def reset_gate() -> None:
    """글로벌 Gate 상태 초기화."""
    _gate.reset()
    _sync_from_gate()


# ══════════════════════════════════════════════════════════════
# 감사 로그
# ══════════════════════════════════════════════════════════════
def audit_init(cluster_name: str, current_ver: str, target_ver: str) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    _gate.audit_lines.extend([
        "# K8s Upgrade Pre-flight Audit Log",
        "# Generated by gate_check.py (deterministic)",
        f"# Cluster: {cluster_name}",
        f"# Upgrade: {current_ver} → {target_ver}",
        f"# Started: {now}",
        "# ──────────────────────────────────────────",
    ])
    _sync_from_gate()


def audit_write(rule_id: str, result: str, detail: str) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    _gate.audit_lines.append(f"{now} | {rule_id} | {result} | {detail}")
    _sync_from_gate()


def audit_flush(path: str) -> None:
    _sync_to_gate()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    gate = "BLOCKED" if _gate.critical_fail > 0 else ("WARN" if _gate.high_warn > 0 else "OPEN")
    _gate.audit_lines.extend([
        "# ──────────────────────────────────────────",
        f"# Summary: CRITICAL_FAIL={_gate.critical_fail} HIGH_WARN={_gate.high_warn} MEDIUM_INFO={_gate.medium_info} PASS={_gate.total_pass}/{_gate.total_rules}",
        f"# Gate: {gate}",
        f"# Finished: {now}",
    ])
    new_content = "\n".join(_gate.audit_lines) + "\n"
    with open(path, "a", encoding="utf-8") as f:
        f.write(new_content)
    _sync_from_gate()


# ══════════════════════════════════════════════════════════════
# 결과 기록
# ══════════════════════════════════════════════════════════════
def record(rule_id: str, severity: str, result: str, detail: str) -> None:
    global critical_fail, high_warn, medium_info, total_pass, total_rules
    _sync_to_gate()
    _gate.total_rules += 1

    if result == "PASS" or result == "SKIP":
        _gate.total_pass += 1
        icon = f"{GREEN}✅ PASS{NC}" if result == "PASS" else f"{CYAN}⏭️  SKIP{NC}"
        print(f"{icon}  {rule_id:<8s} {detail}")
    elif result == "FAIL":
        if severity == "CRITICAL":
            _gate.critical_fail += 1
            print(f"{RED}❌ FAIL{NC}  {rule_id:<8s} [{severity}] {detail}")
        elif severity == "HIGH":
            _gate.high_warn += 1
            print(f"{YELLOW}⚠️  WARN{NC}  {rule_id:<8s} [{severity}] {detail}")
        else:
            # MEDIUM / LOW — 보고만, Gate 판정에 영향 없음
            _gate.medium_info += 1
            print(f"{CYAN}ℹ️  INFO{NC}  {rule_id:<8s} [{severity}] {detail}")

    audit_write(rule_id, result, detail)
    _sync_from_gate()


# ══════════════════════════════════════════════════════════════
# CLI 헬퍼
# ══════════════════════════════════════════════════════════════
def run_cmd(args: list[str], timeout: int = 30) -> subprocess.CompletedProcess:
    """subprocess wrapper — 실패 시 빈 stdout 반환."""
    try:
        return subprocess.run(args, capture_output=True, text=True, timeout=timeout)
    except (subprocess.TimeoutExpired, FileNotFoundError) as e:
        return subprocess.CompletedProcess(args, returncode=1, stdout="", stderr=str(e))


def kubectl_json(resource: str, all_ns: bool = True, timeout: int = 30) -> dict:
    """kubectl get <resource> -o json 실행 후 dict 반환."""
    cmd = ["kubectl", "get", resource, "-o", "json"]
    if all_ns:
        cmd.insert(2, "-A")
    r = run_cmd(cmd, timeout=timeout)
    if r.returncode != 0:
        return {}
    try:
        return json.loads(r.stdout)
    except json.JSONDecodeError:
        return {}


# ══════════════════════════════════════════════════════════════
# 리소스 파서
# ══════════════════════════════════════════════════════════════
def _parse_cpu(s: str) -> int:
    """CPU 문자열 → 밀리코어."""
    if not s:
        return 0
    if s.endswith("m"):
        return int(s[:-1])
    try:
        return int(float(s) * 1000)
    except ValueError:
        return 0


def _parse_mem(s: str) -> int:
    """메모리 문자열 → MiB."""
    if not s:
        return 0
    if s.endswith("Ki"):
        return int(s[:-2]) // 1024
    if s.endswith("Mi"):
        return int(s[:-2])
    if s.endswith("Gi"):
        return int(float(s[:-2]) * 1024)
    if s.endswith("M"):
        return int(s[:-1]) * 1_000_000 // (1024 * 1024)
    try:
        return int(s) // (1024 * 1024)
    except ValueError:
        return 0
